apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-config-server-app
  labels:
    app: cloud-config-server-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-config-server-app
  template:
    metadata:
      labels:
        app: cloud-config-server-app
    spec:
      imagePullSecrets:
        - name: gcr-json-key
      containers:
        - name: cloud-config-server-app
          image: us.gcr.io/balmy-particle-334205/cloud-config-server-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9296

---
apiVersion: v1
kind: Service
metadata:
  name: cloud-config-server-svc
spec:
  ports:
    - targetPort: 9296
      port: 80
  selector:
    app: cloud-config-server-app
