apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-app
  labels:
    app: user-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app : user-service-app
  template:
    metadata:
      labels:
        app: user-service-app
    spec:
      imagePullSecrets:
        - name: gcr-json-key
      containers:
      - name: user-service-app
        image: us.gcr.io/balmy-particle-334205/user-service-app:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 9002

---

kind: Service
apiVersion: v1
metadata:
  name:  user-service-svc
spec:
  selector:
    app:  user-service-app
  ports:
  - port:  80
    targetPort:  9002
